import { Printer, Download, X } from "lucide-react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import ReceiptTemplate from "./ReceiptTemplate";

const ReceiptModal = ({ bill, onClose }) => {
    const exportPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Indigo-600
        doc.text("RentFlow Monthly Invoice", 105, 20, { align: "center" });

        doc.setFontSize(12);
        doc.setTextColor(100, 116, 139); // Slate-500
        doc.text(`Month: ${bill.month}`, 105, 30, { align: "center" });

        // Renter Info
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(`Renter: ${bill.name}`, 20, 45);
        doc.text(`Room No: ${bill.room_number}`, 20, 52);

        // Billing Table
        const tableData = [
            ["Meter Readings", `${bill.previous_reading} to ${bill.current_reading}`],
            ["Units Used", `${bill.units_used} units`],
            ["Description", "Amount (৳)"],
            ["Monthly Rent", bill.monthly_rent.toLocaleString()],
            ["Electricity Bill", bill.electricity_bill.toLocaleString()],
            ["Toilet Fee", bill.toilet_fee.toLocaleString()],
            ["Garbage Bill", bill.garbage_bill.toLocaleString()],
            ["Kitchen Bill", bill.kitchen_bill.toLocaleString()],
            ["Service Charge", bill.service_charge.toLocaleString()],
            ["Previous Due", bill.previous_due.toLocaleString()],
            [{ content: "Total Amount", styles: { fontStyle: 'bold' } }, { content: bill.total_bill.toLocaleString(), styles: { fontStyle: 'bold' } }]
        ];

        doc.autoTable({
            startY: 60,
            head: [["Item", "Details"]],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229] },
            margin: { left: 20, right: 20 }
        });

        // Footer
        const finalY = doc.lastAutoTable.finalY + 20;
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Thank you for your payment!", 105, finalY, { align: "center" });
        doc.text("Generated by RentFlow", 105, finalY + 10, { align: "center" });

        doc.save(`Receipt_${bill.room_number}_${bill.month}.pdf`);
    };

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[60] p-4">
            <div className="bg-white dark:bg-slate-900 w-full max-w-2xl rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[95vh]">
                <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between no-print">
                    <h2 className="text-xl font-bold">ভাড়ার রশিদ</h2>
                    <div className="flex items-center gap-2">
                        <button
                            onClick={exportPDF}
                            className="p-2 text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-900/30 rounded-lg transition-colors"
                            title="Download PDF"
                        >
                            <Download size={20} />
                        </button>
                        <button
                            onClick={handlePrint}
                            className="p-2 text-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"
                            title="Print"
                        >
                            <Printer size={20} />
                        </button>
                        <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 ml-2">
                            <X size={20} />
                        </button>
                    </div>
                </div>

                <div className="overflow-y-auto flex-1 bg-white printable-receipt">
                    <style>{`
            @media print {
              .no-print { display: none !important; }
              body { background: white !important; }
              .printable-receipt { padding: 0 !important; width: 100% !important; height: auto !important; }
            }
          `}</style>

                    <ReceiptTemplate bill={bill} />
                </div>
            </div>
        </div>
    );
};

export default ReceiptModal;
